console.log('🎯 Stripe Product Seeding (Mock Mode)')
console.log('=====================================')
console.log('')
console.log('In production, this would create the following Stripe products:')
console.log('')
console.log('📦 Main Product: Ad Pack')
console.log('   - Name: "Ad Pack"')
console.log('   - Description: "5 TikTok-ready ads with professional voiceovers and captions"')
console.log('   - Price: $149.00')
console.log('   - Type: One-time payment')
console.log('')
console.log('➕ Add-on Products:')
console.log('   1. Instagram Reel Crops (+$39)')
console.log('      - 1:1 square versions for Instagram feed')
console.log('')
console.log('   2. SRT Caption Files (+$19)')
console.log('      - Separate caption files for editing')
console.log('')
console.log('🔧 Next Steps:')
console.log('1. Get your Stripe API keys from https://dashboard.stripe.com/test/apikeys')
console.log('2. Update your .env.local file with:')
console.log('   STRIPE_SECRET_KEY=sk_test_your_actual_key_here')
console.log('   STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here')
console.log('3. Run: pnpm seed:stripe')
console.log('4. Copy the PRICE_AD_PACK value to your .env.local file')
console.log('')
console.log('✅ Mock seeding complete! The app will work in development mode without Stripe.')
